# Generated by Django 2.2.15 on 2022-09-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('url', models.TextField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('condominium', models.FloatField(null=True)),
                ('property_tax', models.FloatField(null=True)),
                ('useful_area', models.CharField(max_length=50, null=True)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('parking_spaces', models.IntegerField()),
                ('postal_code', models.CharField(max_length=100, null=True)),
                ('county', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('date_reference', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
