# Generated by Django 2.2.15 on 2022-04-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_station_name', models.CharField(max_length=50)),
                ('datetime_reference', models.DateTimeField(auto_now_add=True)),
                ('gas_price', models.FloatField()),
            ],
        ),
    ]
