# Generated by Django 2.2.15 on 2022-04-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasprice',
            name='gas_station_name',
        ),
        migrations.AddField(
            model_name='gasprice',
            name='ethanol_higher_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gasprice',
            name='ethanol_lower_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gasprice',
            name='ethanol_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gasprice',
            name='gas_higher_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gasprice',
            name='gas_lower_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gasprice',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gasprice',
            name='datetime_reference',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='gasprice',
            name='gas_price',
            field=models.FloatField(null=True),
        ),
    ]
