# Generated by Django 2.2.15 on 2022-04-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0002_auto_20220406_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasprice',
            name='datetime_reference',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
