# Generated by Django 2.1.4 on 2022-03-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMWOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('url', models.TextField()),
                ('car_model', models.CharField(max_length=100, null=True)),
                ('car_year', models.IntegerField()),
                ('km', models.IntegerField(null=True)),
                ('power', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('seller_name', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
